# webhook-deployment.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-validation-webhook
webhooks:
- name: webhook-service.webhooks.svc.cluster.local
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["pods"]
  clientConfig:
    service:
      name: webhook-service
      namespace: webhooks
      path: "/validate"
      port: 8443
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lVQ2tZbi9PZnFzV25RRDRDUWJyV0t2ZDV6SXhBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tWMlZpYUc5dmF5QkRRVEFlRncweU5UQTBNVFV4TWpVeU1EUmFGdzB5TlRBMQpNVFV4TWpVeU1EUmFNQlV4RXpBUkJnTlZCQU1NQ2xkbFltaHZiMnNnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDYWlqU1ZHR0paTVc0RWFneS90RDBnaW5RZlhJT29EYVIvQlgzNnJxYXgKVEw5aFRIN1YyeTcxU2JEcFo0QkhiL2R3VUVjWXNhU3FkdGZadFUrNWk5RFkvamxWTmRySXVSVDRCNnFmZDRhZgpsd1h0Vnk2ZEJjM1hvSnAwak5XVzRmOEpMWE9GQ1Nhd3A2dFFycTZhTGVvWWZyaEYxRjVDaTV1NHlqejN6TFU1Ck5JMzdkOTJQb3BpOHB6UFpON0lLR1BNTU9KN2svaVk5aDdwQ3ZxVkNDTDhLWWJWVUlDdkVZRjVWRFROdEZ5aHQKUzRmSkUveTNGcCthNExTNCtjYVFJUkRBNkpneXFyZ3pYakd1bVQ0bnFON3VISStaTFo5dnJpTjFXV3RTS2p0aAp0MzBiWlhnbnpTWmViNkNtckJZbVN6WGozUVBXb203UHBJbGpROWtrbGxXakFnTUJBQUdqVXpCUk1CMEdBMVVkCkRnUVdCQlFIQkd1LzlKSkVyV3lWTjluTmxMY3cvZWp2clRBZkJnTlZIU01FR0RBV2dCUUhCR3UvOUpKRXJXeVYKTjluTmxMY3cvZWp2clRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDUwpvaGJhM0dBblEwejdaekN3bjR5Z2hFeE11SUYyN01tNVg4YWVmOVFEY0dBVCtjbmMwcGExNzRDN0NyWlplSUppCm1yWVowYW4wR21nY2xHcVNTUU9xRWcxRjFNU1RPWGZqYmdhYnhrR0x2aGk5QWxmNXZjU0RvWFhuQWRaeVBTeWQKeVhDZzM3cUtkSnE1eStRbWF4eUxrYXlBY3k4N2U4V0hxSEFmT0pvcHAvTGdlVUJxcUEyQmgzMTE2TVQ2M1h1cAp0VXJFSVQ4TnJPVVM2cnpxRnVQSXZkSEZlUVlQMzhOaDhsd2NCSXV2VE14OHl2Q3o4ZnpJdmpLWWNzdVhGNC9NClIrZWhCY2xWZzhOS2hTNHZpVkZNVHBZUTNMbHVWalVLQ2hKVkFGUEhXVlBZa1hLcW45RUVpWDNPL3VZMlJ4K3YKcDRZNXIrZnUzRmZ3ai83Y2w4azUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  admissionReviewVersions: ["v1"]
  failurePolicy: Fail  # Reject if webhook is down
  sideEffects: None


  