

# webhook-deployment.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-validation-webhook
webhooks:
- name: example-webhook.default.svc.cluster.local
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["pods"]
  clientConfig:
    service:
      name: webhook-service
      namespace: webhooks
      path: "/validate"
      port: 8443
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN2akNDQWFZQ0ZINlZmR1IvcUd6Zk5WMnpaRTdzTUNST3Y3OWJNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1CQXgKRGpBTUJnTlZCQU1NQlUxNUlFTkJNQjRYRFRJMU1EUXhOREl4TWpVMU1Wb1hEVEkyTURReE5ESXhNalUxTVZvdwpKekVsTUNNR0ExVUVBd3djZDJWaWFHOXZheTF6WlhKMmFXTmxMbmRsWW1odmIydHpMbk4yWXpDQ0FTSXdEUVlKCktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUtpUVUrREN0YjdsYWZQZ25uZkZLVndaZy9pU3JUMm4KVlpZSC80TXZrOHhnakR6dGIzSG5wcXczTW5JZWU0R0pLQVcrd0graEp6enJFc0tDV3RJL1d2RVVVL1RtL3dJeApNY3hwZE40a2ZQaXo1WVJzdVNOSHpockt0NEhNTk5iZjA3YkJJSFpkMmEvOEdBVHFtczNHQStLL0N6R3pVblNiCllPa3FtcHU2VlprSmoxOTdhbkVSZ29DcEZOVFNGNTZGcGxzMk1UcW5zT2NBZTVFQWFUWDk2RHN5ajU0OHFybzMKOGtsdEVrSzJIQVBsNkdtOXdqemR5VGdvTVdGQ3lZQngwdXFiaTI0Z2Y1NFZyZmtQRXFpdjR4OENPWDVxOFZOQwpQYjhqSVZIMmMxZDVmK1E5UExLT0FLUkNVbFFBVEpKNTRFVmx5NFdxRk1SYXFoWUM3b2lHZGpNQ0F3RUFBVEFOCkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUV0a0Vrb0Q1UTVVbzVzT0ZOMVg4a1p0MzdocTVzL3NaUGlUUkZyOXEKRUMvenlJaFMrTjBTMnhpTDl0T1g1RjVKcVJ4aXhPV0tBbHFSelpJV0g0K1RlS0NLU0d3dXBaZThGcDI4OTV3YQpsWXU5Z1JycGRLd25FcU1XUzNZREZZNEg1YmlyUUNJc2ZXWnJJcUZSY3BZaFZiN3IzV1hyZk8vQk9aUWpxYWFMClllTnVRWno2VVI0eW1uZzVlZmRHRzQyeDlwekNNdVVoQ1E3cmpzL0NMOCs4YkVucGhUUGpWdm11SlNQeTlpVWgKNHBtT0VyZ1QxdU83WHByb1k0UStnMk8xb2dGTGdXUmwyeGZLczNhRDlneVNGc0NSVEcyYWV6TndvTnFLLytSVAoxbElqSE5vNWZYRVhTWGxuSU4wM2FOZFFBNDREUitGcFFFZzUvTUZBWktDWW1nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  admissionReviewVersions: ["v1"]
  failurePolicy: Fail  # Reject if webhook is down
  sideEffects: None