# webhook-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-service-account
  namespace: webhooks  
---

# webhook-cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-validator-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "update"]
---

# webhook-cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook-pod-validator-binding
subjects:
- kind: ServiceAccount
  name: webhook-service-account
  namespace: webhooks
roleRef:
  kind: ClusterRole
  name: pod-validator-role
  apiGroup: rbac.authorization.k8s.io



